### ISSUE TITLE
Constraint on reducer state type

### ISSUE THREAD

**Issue by aikoven** [slorber/rereduce#4]
I'm a bit concerned about constraint that reducer state can't be primitive. 

Can't we workaround this e.g. by using `WeakMap`?

**Comment by aikoven** [comment]
After reading through source more closely I realized that this constraint is only present for reducers with dependencies, and not for simple memoized reducers.

Anyway, it seems wrong to me that state type is changed implicitly. Maybe we should just throw an error if reducer returns primitive value?

**Comment by slorber** [comment]
@aikoven I don't know what you'd like to do with WeakMap

Yes it's present for reducers with dependencies and is required to store the __dependencies attribute.

I tried something else before but it breaks time-travel so that __dependencies attribute is really required :(

I also don't like this implicit change so much, do you think it's better if the reducer is forbidden to return a primitive value if it has dependencies? I wanted to do that initially but then made it implicit... haha

**Comment by aikoven** [comment]
Yes, I think it would be better. Consider that initial value for state is `null`, but subsequent values are objects. Then we'd end up with different state shape for initial and subsequent states.

I also discovered that `createReducer` doesn't work with state being an array. I'm currently working on PR to fix that, but I also encountered that returned function always expects object of shape `{value: ..., __dependencies: ...}`. Is this intended behaviour? From the docs I thought that state shape is preserved but with added `__dependencies` property. Currently I have to nest state object under `value` prop, even if it's non-primitive.

**Comment by aikoven** [comment]
More thoughts:

We have two options on how to pass dependencies with state:
1. Add `__dependencies` property to state object. 
   
   Pros:
   - State shape is (almost) preserved.
   
   Cons: 
   - State can't be primitive. Fix is required to allow state to be array.
   - Reducer function has access to `state.__dependencies` property and can break things.
2. Always wrap state and dependencies in parent object.
   
   Pros:
   - State can have any type
   - Reducer function can't break things, it can only access dependencies via 3rd argument
   
   Cons:
   - State shape is changed.

So for now I'm thinking that maybe we should always wrap. Also there would be no need to prefix `__dependencies` with underscores, as it's not accessible from reducer function.

**Comment by slorber** [comment]
So finally you changed your mind from "never wrap and forbid primitive values" to "always wrap and avoid exposing __dependencies" right?

**Comment by aikoven** [comment]
Yes, for the sake of consistency and encapsulation of dependencies object.

**Comment by aikoven** [comment]
What do you think? I'm ready to do the PR.

**Comment by slorber** [comment]
yes why not
