### ISSUE TITLE
Using with redux-thunk

### ISSUE THREAD

**Issue by pronebird** [slorber/rereduce#9]
Does it work with redux-thunk? I can't seem to be able to return a function from reducer.

**Comment by slorber** [comment]
it's a reducer so it's not related to redux-thunk in any way. I don't really know what you are trying to achieve

**Comment by pronebird** [comment]
For some reason redux-thunk does not work and my state gets trashed with undefined when I return a function from action. But I don't think it's related to rereduce since I removed it and it didn't help.

**Comment by slorber** [comment]
Yeah I don't think it can be related in any way, the reducer just receives action, the thunk part is more related to emitting them
